services:
  postgres:
    image: 'postgres:17-alpine'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=crm
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    env_file:
      - .env
    ports:
      - '5672:5672'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
      
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 64M


volumes:
  postgres_data:
