services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=crm
    ports:
      - '5433:5432'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  rabbitmq:
    image: 'rabbitmq:latest'
    env_file:
      - .env
    ports:
      - '5672:5672'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
